export const LevelsDB = {
  title: 'Levels',
  type: 'levels',
  content: [
    {
      id: 1,
      name: 'Training Level',
      targetScore: 1001,
      image: '🚀',
      reward: 'Base PPS doubles',
      rewardEffect: 1,
      rewardType: 'pointsPerSecond',
      desc: 'A world of sandbox where you learn the game',
      fuelUnlocked: false,
      powerUnlocked: false,
    },
    {
      id: 2,
      name: 'Forest Level',
      targetScore: 10000000,
      image: '🚀',
      reward: 'PPS doubles',
      rewardEffect: 1,
      rewardType: 'pointsPerSecond',
      desc: 'A world of sandbox where you learn the game',
      fuelUnlocked: false,
      powerUnlocked: false,
    },
    {
      id: 3,
      name: 'Scuba Level',
      image: '🚀',
      reward: 'PPS doubles',
      rewardEffect: 1,
      rewardType: 'pointsPerSecond',
      desc: 'A world of sandbox where you learn the game',
      fuelUnlocked: false,
      powerUnlocked: false,
    },
  ],
};
